name: Terraform Plan

on:
  pull_request:
    branches:
      - main
      - staging
      - develop
      - feature
    types: [opened, synchronize]

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: Determine environment
        id: set-env
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.base_ref }}" == "staging" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          elif [[ "${{ github.base_ref }}" == "develop" ]]; then
            echo "environment=development" >> $GITHUB_OUTPUT
          fi
  plan:
    needs: determine-environment
    uses: ./.github/workflows/terraform-reusable.yml
    # Add permissions for OIDC
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: write
    with:
      environment: ${{ needs.determine-environment.outputs.environment }}
      pr_number: ${{ github.event.pull_request.number }}
      trigger_ref: ${{ github.head_ref }}
      is_apply: true